# Generated by Django 5.0.7 on 2024-08-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userinfo_id_alter_userinfo_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='pics/'),
        ),
    ]
