# Generated by Django 5.0.7 on 2024-09-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userinfo_bio_alter_userinfo_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='bio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
