# Generated by Django 5.0.7 on 2024-11-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_username_userinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_image',
            field=models.ImageField(default='pics/placeholder.jpg', null=True, upload_to='pics/'),
        ),
    ]
