# Generated by Django 5.0.7 on 2024-08-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_blog_author_alter_blog_description_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='pic.png', upload_to='pics/'),
        ),
    ]
