# Generated by Django 5.0.7 on 2024-08-12 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 12, 8, 38, 3, 666850)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='pics/placeholder.png', null=True, upload_to='pics/'),
        ),
    ]
