# Generated by Django 5.0.7 on 2024-08-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='pics/placeholder.png', null=True, upload_to='pics/'),
        ),
    ]
