# Generated by Django 5.0.7 on 2024-08-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='username',
            field=models.CharField(max_length=60),
        ),
    ]
