# Generated by Django 5.0.7 on 2024-08-28 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
