# Generated by Django 5.0.7 on 2024-11-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
