# Generated by Django 5.0.7 on 2024-11-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0017_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='time_created',
            field=models.TimeField(),
        ),
    ]
